"use client";

import { useState, useMemo } from "react";
import ToolFaqAccordion from "@/components/ToolFaqAccordion";

export default function RedirectHtaccessGeneratorPage() {
  const [activeTab, setActiveTab] = useState("url"); // 'url', 'https', 'www', 'domain', 'slash', 'security', 'errors'
  const [serverType, setServerType] = useState("apache"); // 'apache', 'nginx', 'cloudflare'

  // URL Redirect State
  const [redirectType, setRedirectType] = useState("301");
  const [oldPath, setOldPath] = useState("/old-seo-service-page");
  const [newPath, setNewPath] = useState("/services/technical-seo");
  const [preserveQuery, setPreserveQuery] = useState(true);

  // WWW & HTTPS State
  const [domainName, setDomainName] = useState("example.com");
  const [wwwOption, setWwwOption] = useState("force-non-www"); // 'force-non-www', 'force-www'
  const [forceHttps, setForceHttps] = useState(true);

  // Domain Migration State
  const [oldDomain, setOldDomain] = useState("oldsite.com");
  const [newDomain, setNewDomain] = useState("newsite.com");

  // Trailing Slash State
  const [slashOption, setSlashOption] = useState("add"); // 'add', 'remove'

  // Security & Bot State
  const [blockBadBots, setBlockBadBots] = useState(true);
  const [protectDotFiles, setProtectDotFiles] = useState(true);
  const [disableDirectoryListing, setDisableDirectoryListing] = useState(true);

  // Custom Errors State
  const [error404Path, setError404Path] = useState("/404.html");
  const [error500Path, setError500Path] = useState("/500.html");

  const [copied, setCopied] = useState(false);

  // Generated Code Logic
  const generatedCode = useMemo(() => {
    let cleanOld = oldPath.trim();
    if (!cleanOld.startsWith("/")) cleanOld = "/" + cleanOld;
    let cleanNew = newPath.trim();

    if (serverType === "apache") {
      let code = `# ========================================================\n# Generated by Abdullahbdseo .htaccess Generator\n# Safe, Canonical & Performance-Optimized Directives\n# ========================================================\n\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteBase /\n\n`;

      if (activeTab === "url") {
        code += `# --- ${redirectType} Redirect for Page URL ---\n`;
        const codeNum = redirectType === "301" ? "301,L" : "302,L";
        const oldRegex = cleanOld.replace(/^\//, "^").replace(/\//g, "\\/") + "$";
        code += `RewriteRule ${oldRegex} ${cleanNew} [R=${codeNum}${preserveQuery ? ",QSA" : ""}]\n`;
      } else if (activeTab === "https") {
        code += `# --- Force HTTPS (SSL) Rewrite ---\n`;
        code += `RewriteCond %{HTTPS} off\n`;
        code += `RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n`;
      } else if (activeTab === "www") {
        if (wwwOption === "force-non-www") {
          code += `# --- Force Non-WWW (Canonical Domain) ---\n`;
          code += `RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]\n`;
          code += `RewriteRule ^(.*)$ https://%1/$1 [R=301,L]\n`;
        } else {
          code += `# --- Force WWW ---\n`;
          code += `RewriteCond %{HTTP_HOST} !^www\\. [NC]\n`;
          code += `RewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]\n`;
        }
      } else if (activeTab === "domain") {
        code += `# --- Full Domain 301 Migration (Preserve Paths) ---\n`;
        code += `RewriteCond %{HTTP_HOST} ^(www\\.)?${oldDomain.replace(/\./g, "\\.")}$ [NC]\n`;
        code += `RewriteRule ^(.*)$ https://${newDomain}/$1 [R=301,L]\n`;
      } else if (activeTab === "slash") {
        if (slashOption === "add") {
          code += `# --- Force Trailing Slash on URLs ---\n`;
          code += `RewriteCond %{REQUEST_FILENAME} !-f\n`;
          code += `RewriteCond %{REQUEST_URI} !(.*)/$\n`;
          code += `RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1/ [L,R=301]\n`;
        } else {
          code += `# --- Remove Trailing Slash from URLs ---\n`;
          code += `RewriteCond %{REQUEST_FILENAME} !-d\n`;
          code += `RewriteCond %{REQUEST_URI} (.+)/$\n`;
          code += `RewriteRule ^(.+)/$ https://%{HTTP_HOST}/$1 [R=301,L]\n`;
        }
      } else if (activeTab === "security") {
        code += `</IfModule>\n\n`;
        if (disableDirectoryListing) {
          code += `# Disable Directory Browsing\nOptions -Indexes\n\n`;
        }
        if (protectDotFiles) {
          code += `# Block Access to Sensitive Files (.env, .git, .htaccess, wp-config)\n<FilesMatch "^(\\.|wp-config\\.php|composer\\.json|package\\.json)">\n  Require all denied\n</FilesMatch>\n\n`;
        }
        if (blockBadBots) {
          code += `<IfModule mod_rewrite.c>\nRewriteEngine On\n# Block Vulnerability Scanners & Bad AI Crawlers\nRewriteCond %{HTTP_USER_AGENT} (SemrushBot|AhrefsBot|DotBot|MJ12bot|MegaIndex|Bytespider) [NC]\nRewriteRule .* - [F,L]\n`;
        }
      } else if (activeTab === "errors") {
        code += `</IfModule>\n\n# Custom Server Error Handlers\nErrorDocument 404 ${error404Path}\nErrorDocument 500 ${error500Path}\n`;
        return code;
      }

      if (activeTab !== "errors" && activeTab !== "security") {
        code += `</IfModule>\n`;
      } else if (activeTab === "security" && blockBadBots) {
        code += `</IfModule>\n`;
      }

      return code;
    } else if (serverType === "nginx") {
      let code = `# Nginx Server Configuration Block\n# Place inside your server { ... } block\n\n`;

      if (activeTab === "url") {
        const flag = redirectType === "301" ? "permanent" : "redirect";
        code += `# ${redirectType} URL Redirect\n`;
        code += `rewrite ^${cleanOld}$ ${cleanNew} ${flag};\n`;
      } else if (activeTab === "https") {
        code += `# Force HTTPS in Nginx\n`;
        code += `return 301 https://$host$request_uri;\n`;
      } else if (activeTab === "www") {
        if (wwwOption === "force-non-www") {
          code += `server {\n    server_name www.${domainName};\n    return 301 https://${domainName}$request_uri;\n}\n`;
        } else {
          code += `server {\n    server_name ${domainName};\n    return 301 https://www.${domainName}$request_uri;\n}\n`;
        }
      } else if (activeTab === "domain") {
        code += `server {\n    server_name ${oldDomain} www.${oldDomain};\n    return 301 https://${newDomain}$request_uri;\n}\n`;
      } else if (activeTab === "slash") {
        if (slashOption === "add") {
          code += `# Force Trailing Slash\nrewrite ^([^.\\?]*[^/])$ $1/ permanent;\n`;
        } else {
          code += `# Remove Trailing Slash\nrewrite ^/(.*)/$ /$1 permanent;\n`;
        }
      } else if (activeTab === "security") {
        code += `# Deny Hidden & Sensitive Files\nlocation ~ /\\.(?!well-known).* {\n    deny all;\n}\n\n# Block Bad Crawlers\nif ($http_user_agent ~* (SemrushBot|AhrefsBot|DotBot|MJ12bot|Bytespider)) {\n    return 403;\n}\n`;
      } else if (activeTab === "errors") {
        code += `error_page 404 ${error404Path};\nerror_page 500 502 503 504 ${error500Path};\n`;
      }

      return code;
    } else if (serverType === "cloudflare") {
      let code = `// Cloudflare Redirect Rule Configuration (Bulk Redirects / Transform Rules)\n\n`;
      if (activeTab === "url") {
        code += `When incoming requests match:\n(http.request.uri.path eq "${cleanOld}")\n\nAction: Dynamic Redirect (301)\nTarget URL: "${cleanNew}"\nPreserve query string: ${preserveQuery ? "Enabled" : "Disabled"}\n`;
      } else if (activeTab === "https") {
        code += `Cloudflare Dashboard:\nSSL/TLS -> Edge Certificates -> Enable "Always Use HTTPS" (Automatic 301)\n`;
      } else if (activeTab === "www") {
        const from = wwwOption === "force-non-www" ? `www.${domainName}/*` : `${domainName}/*`;
        const to = wwwOption === "force-non-www" ? `https://${domainName}/$1` : `https://www.${domainName}/$1`;
        code += `Cloudflare Page Rule:\nMatch URL: *${from}\nSetting: Forwarding URL (Status 301 - Permanent Redirect)\nDestination URL: ${to}\n`;
      } else if (activeTab === "domain") {
        code += `Cloudflare Page Rule:\nMatch URL: *${oldDomain}/*\nSetting: Forwarding URL (301 Permanent Redirect)\nDestination URL: https://${newDomain}/$2\n`;
      } else {
        code += `Use Cloudflare Transform Rules (URL Rewrite) or Page Rules for custom path manipulation.\n`;
      }
      return code;
    }

    return "";
  }, [
    activeTab,
    serverType,
    redirectType,
    oldPath,
    newPath,
    preserveQuery,
    domainName,
    wwwOption,
    forceHttps,
    oldDomain,
    newDomain,
    slashOption,
    blockBadBots,
    protectDotFiles,
    disableDirectoryListing,
    error404Path,
    error500Path,
  ]);

  const copyToClipboard = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(generatedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadHtaccess = () => {
    const element = document.createElement("a");
    const file = new Blob([generatedCode], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = serverType === "nginx" ? "nginx-redirects.conf" : ".htaccess";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const faqs = [
    {
      q: "What is the difference between a 301 and 302 redirect?",
      a: "A 301 redirect is a Permanent Redirect that passes 90% to 99% of SEO link equity (PageRank) from the old URL to the new URL. A 302 redirect is Temporary and tells search engines to keep the old URL indexed in search results without transferring link equity."
    },
    {
      q: "Where do I put the generated .htaccess code on my server?",
      a: "For Apache and LiteSpeed web servers, place the `.htaccess` file in your website's root directory (typically `public_html/` or `www/`). Ensure mod_rewrite is enabled on your hosting."
    },
    {
      q: "Why is Non-WWW to WWW (or vice-versa) canonicalization critical for SEO?",
      a: "Google treats 'example.com' and 'www.example.com' as two distinct websites. Without a 301 redirect rule enforcing one primary canonical version, your search authority splits in half, creating duplicate content indexation issues."
    },
    {
      q: "Does a 301 domain migration preserve Google search rankings?",
      a: "Yes. When migrating to a new domain name, using wildcard 301 redirects combined with Google Search Console's 'Change of Address' tool transfers your existing rankings, organic traffic, and backlink authority smoothly."
    }
  ];

  return (
    <div className="tool-page-container" style={{ maxWidth: "1200px", margin: "0 auto", padding: "40px 20px 80px" }}>
      {/* HEADER */}
      <div style={{ textAlign: "center", marginBottom: "36px" }}>
        <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "#fef3c7", color: "#d97706", padding: "6px 14px", borderRadius: "4px", fontSize: "0.85rem", fontWeight: 700, marginBottom: "12px", border: "1px solid #fde68a" }}>
          <i className="fa-solid fa-arrow-right-arrow-left"></i> Server Redirects &amp; Canonical Rewrite Suite
        </div>
        <h1 style={{ fontSize: "2.4rem", fontWeight: 900, color: "#0f172a", marginBottom: "12px", lineHeight: 1.2 }}>
          301 Redirect &amp; <span style={{ color: "#2563eb" }}>.htaccess Generator</span>
        </h1>
        <p style={{ fontSize: "1.05rem", color: "#475569", maxWidth: "780px", margin: "0 auto", lineHeight: 1.6 }}>
          Generate battle-tested Apache `.htaccess`, Nginx rewrite, and Cloudflare rules for 301 URL migrations, HTTPS enforcement, WWW canonicalization, and trailing slash compliance.
        </p>

        {/* SERVER SELECTOR */}
        <div style={{ display: "inline-flex", background: "#f1f5f9", padding: "4px", borderRadius: "4px", border: "1px solid #e2e8f0", marginTop: "24px" }}>
          {[
            { id: "apache", label: "Apache (.htaccess)", icon: "fa-server" },
            { id: "nginx", label: "Nginx (nginx.conf)", icon: "fa-bolt" },
            { id: "cloudflare", label: "Cloudflare Rules", icon: "fa-cloud" },
          ].map((s) => (
            <button
              key={s.id}
              type="button"
              onClick={() => setServerType(s.id)}
              style={{
                padding: "8px 18px",
                borderRadius: "4px",
                border: "none",
                fontSize: "0.88rem",
                fontWeight: 700,
                cursor: "pointer",
                background: serverType === s.id ? "#2563eb" : "transparent",
                color: serverType === s.id ? "#ffffff" : "#475569",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                transition: "all 0.2s ease",
              }}
            >
              <i className={`fa-solid ${s.icon}`}></i>
              {s.label}
            </button>
          ))}
        </div>
      </div>

      {/* FEATURE SCENARIO TABS */}
      <div style={{ display: "flex", gap: "8px", overflowX: "auto", paddingBottom: "12px", marginBottom: "24px" }}>
        {[
          { id: "url", label: "URL to URL Redirect", icon: "fa-link" },
          { id: "https", label: "Force HTTPS (SSL)", icon: "fa-lock" },
          { id: "www", label: "WWW Canonicalization", icon: "fa-globe" },
          { id: "domain", label: "Domain Migration", icon: "fa-right-left" },
          { id: "slash", label: "Trailing Slash Rules", icon: "fa-slash" },
          { id: "security", label: "Security & Bad Bots", icon: "fa-shield-halved" },
          { id: "errors", label: "Custom Error Pages", icon: "fa-triangle-exclamation" },
        ].map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            style={{
              padding: "10px 16px",
              borderRadius: "4px",
              border: activeTab === tab.id ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
              background: activeTab === tab.id ? "#eff6ff" : "#ffffff",
              color: activeTab === tab.id ? "#2563eb" : "#334155",
              fontWeight: 700,
              fontSize: "0.86rem",
              cursor: "pointer",
              whiteSpace: "nowrap",
              display: "flex",
              alignItems: "center",
              gap: "8px",
            }}
          >
            <i className={`fa-solid ${tab.icon}`}></i>
            {tab.label}
          </button>
        ))}
      </div>

      {/* MAIN GENERATOR INTERFACE */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))", gap: "28px", alignItems: "start" }}>
        {/* CONFIG CONTROLS */}
        <div style={{ background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: "4px", padding: "28px", boxShadow: "0 4px 20px rgba(0,0,0,0.03)" }}>
          <h3 style={{ fontSize: "1.15rem", fontWeight: 800, color: "#0f172a", marginBottom: "20px" }}>
            ⚙️ Configure Redirect Rules
          </h3>

          {/* TAB 1: URL TO URL */}
          {activeTab === "url" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Redirect Status Code
                </label>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                  <button
                    type="button"
                    onClick={() => setRedirectType("301")}
                    style={{
                      padding: "8px",
                      borderRadius: "4px",
                      border: redirectType === "301" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: redirectType === "301" ? "#eff6ff" : "#ffffff",
                      color: redirectType === "301" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    301 Permanent (SEO Best)
                  </button>
                  <button
                    type="button"
                    onClick={() => setRedirectType("302")}
                    style={{
                      padding: "8px",
                      borderRadius: "4px",
                      border: redirectType === "302" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: redirectType === "302" ? "#eff6ff" : "#ffffff",
                      color: redirectType === "302" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    302 Temporary
                  </button>
                </div>
              </div>

              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Old Relative Path (Source URL)
                </label>
                <input
                  type="text"
                  value={oldPath}
                  onChange={(e) => setOldPath(e.target.value)}
                  placeholder="/old-page-name"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>

              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  New Destination Path or Full URL
                </label>
                <input
                  type="text"
                  value={newPath}
                  onChange={(e) => setNewPath(e.target.value)}
                  placeholder="/services/new-target-page"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>

              <div style={{ display: "flex", alignItems: "center", gap: "10px", marginTop: "4px" }}>
                <input
                  type="checkbox"
                  id="query_cb"
                  checked={preserveQuery}
                  onChange={(e) => setPreserveQuery(e.target.checked)}
                  style={{ width: "18px", height: "18px", accentColor: "#2563eb", cursor: "pointer" }}
                />
                <label htmlFor="query_cb" style={{ fontSize: "0.85rem", color: "#334155", fontWeight: 600, cursor: "pointer" }}>
                  Preserve Query Parameters (?utm_source=..., etc.)
                </label>
              </div>
            </div>
          )}

          {/* TAB 2: FORCE HTTPS */}
          {activeTab === "https" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div style={{ background: "#ecfdf5", border: "1px solid #a7f3d0", padding: "16px", borderRadius: "4px" }}>
                <strong style={{ color: "#065f46", fontSize: "0.9rem", display: "block", marginBottom: "4px" }}>
                  🔒 SSL Automatic 301 Enforcement
                </strong>
                <p style={{ color: "#047857", fontSize: "0.85rem", margin: 0, lineHeight: 1.5 }}>
                  Redirects all insecure `http://` traffic to secure `https://` with a 301 Permanent header to satisfy Google HTTPS ranking requirements.
                </p>
              </div>
            </div>
          )}

          {/* TAB 3: WWW VS NON-WWW */}
          {activeTab === "www" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Domain Name
                </label>
                <input
                  type="text"
                  value={domainName}
                  onChange={(e) => setDomainName(e.target.value)}
                  placeholder="example.com"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>

              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Canonical Host Preference
                </label>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                  <button
                    type="button"
                    onClick={() => setWwwOption("force-non-www")}
                    style={{
                      padding: "10px",
                      borderRadius: "4px",
                      border: wwwOption === "force-non-www" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: wwwOption === "force-non-www" ? "#eff6ff" : "#ffffff",
                      color: wwwOption === "force-non-www" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    Force Non-WWW (example.com)
                  </button>
                  <button
                    type="button"
                    onClick={() => setWwwOption("force-www")}
                    style={{
                      padding: "10px",
                      borderRadius: "4px",
                      border: wwwOption === "force-www" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: wwwOption === "force-www" ? "#eff6ff" : "#ffffff",
                      color: wwwOption === "force-www" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    Force WWW (www.example.com)
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: DOMAIN MIGRATION */}
          {activeTab === "domain" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Old Domain (Source)
                </label>
                <input
                  type="text"
                  value={oldDomain}
                  onChange={(e) => setOldDomain(e.target.value)}
                  placeholder="oldsite.com"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  New Domain (Target Destination)
                </label>
                <input
                  type="text"
                  value={newDomain}
                  onChange={(e) => setNewDomain(e.target.value)}
                  placeholder="newsite.com"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>
            </div>
          )}

          {/* TAB 5: TRAILING SLASH */}
          {activeTab === "slash" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  URL Trailing Slash Strategy
                </label>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                  <button
                    type="button"
                    onClick={() => setSlashOption("add")}
                    style={{
                      padding: "10px",
                      borderRadius: "4px",
                      border: slashOption === "add" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: slashOption === "add" ? "#eff6ff" : "#ffffff",
                      color: slashOption === "add" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    Add Trailing Slash (/page/)
                  </button>
                  <button
                    type="button"
                    onClick={() => setSlashOption("remove")}
                    style={{
                      padding: "10px",
                      borderRadius: "4px",
                      border: slashOption === "remove" ? "1.5px solid #2563eb" : "1px solid #cbd5e1",
                      background: slashOption === "remove" ? "#eff6ff" : "#ffffff",
                      color: slashOption === "remove" ? "#2563eb" : "#475569",
                      fontWeight: 700,
                      fontSize: "0.85rem",
                      cursor: "pointer",
                    }}
                  >
                    Remove Trailing Slash (/page)
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* TAB 6: SECURITY & BOTS */}
          {activeTab === "security" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
              <label style={{ display: "flex", alignItems: "center", gap: "10px", cursor: "pointer" }}>
                <input
                  type="checkbox"
                  checked={blockBadBots}
                  onChange={(e) => setBlockBadBots(e.target.checked)}
                  style={{ width: "18px", height: "18px", accentColor: "#2563eb" }}
                />
                <span style={{ fontSize: "0.88rem", fontWeight: 600, color: "#334155" }}>
                  Block Aggressive SEO Scrapers &amp; Bad Bots (Semrush, Ahrefs, MJ12bot)
                </span>
              </label>

              <label style={{ display: "flex", alignItems: "center", gap: "10px", cursor: "pointer" }}>
                <input
                  type="checkbox"
                  checked={protectDotFiles}
                  onChange={(e) => setProtectDotFiles(e.target.checked)}
                  style={{ width: "18px", height: "18px", accentColor: "#2563eb" }}
                />
                <span style={{ fontSize: "0.88rem", fontWeight: 600, color: "#334155" }}>
                  Deny Direct Access to .env, .git, and wp-config.php Files
                </span>
              </label>

              <label style={{ display: "flex", alignItems: "center", gap: "10px", cursor: "pointer" }}>
                <input
                  type="checkbox"
                  checked={disableDirectoryListing}
                  onChange={(e) => setDisableDirectoryListing(e.target.checked)}
                  style={{ width: "18px", height: "18px", accentColor: "#2563eb" }}
                />
                <span style={{ fontSize: "0.88rem", fontWeight: 600, color: "#334155" }}>
                  Disable Server Directory Browsing (`Options -Indexes`)
                </span>
              </label>
            </div>
          )}

          {/* TAB 7: ERRORS */}
          {activeTab === "errors" && (
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Custom 404 Page Path
                </label>
                <input
                  type="text"
                  value={error404Path}
                  onChange={(e) => setError404Path(e.target.value)}
                  placeholder="/404.html"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>

              <div>
                <label style={{ fontSize: "0.85rem", fontWeight: 700, color: "#334155", display: "block", marginBottom: "6px" }}>
                  Custom 500 Internal Error Page Path
                </label>
                <input
                  type="text"
                  value={error500Path}
                  onChange={(e) => setError500Path(e.target.value)}
                  placeholder="/500.html"
                  style={{ width: "100%", padding: "10px 14px", borderRadius: "4px", border: "1px solid #cbd5e1", fontSize: "0.95rem", color: "#0f172a", outline: "none", fontFamily: "monospace" }}
                />
              </div>
            </div>
          )}
        </div>

        {/* CODE OUTPUT PANEL */}
        <div style={{ background: "#0f172a", borderRadius: "4px", padding: "24px", color: "#f8fafc", boxShadow: "0 10px 30px rgba(15, 23, 42, 0.2)" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "14px", borderBottom: "1px solid #334155", paddingBottom: "12px" }}>
            <span style={{ fontSize: "0.85rem", fontWeight: 700, color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.05em" }}>
              <i className="fa-solid fa-code" style={{ marginRight: "6px", color: "#38bdf8" }}></i>
              {serverType === "apache" ? ".htaccess" : serverType === "nginx" ? "nginx.conf" : "Cloudflare Rule"}
            </span>

            <div style={{ display: "flex", gap: "8px" }}>
              <button
                type="button"
                onClick={copyToClipboard}
                style={{
                  padding: "6px 14px",
                  background: copied ? "#059669" : "#2563eb",
                  color: "#ffffff",
                  border: "none",
                  borderRadius: "4px",
                  fontSize: "0.8rem",
                  fontWeight: 700,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <i className={`fa-solid ${copied ? "fa-check" : "fa-copy"}`}></i>
                {copied ? "Copied!" : "Copy Code"}
              </button>

              <button
                type="button"
                onClick={downloadHtaccess}
                style={{
                  padding: "6px 12px",
                  background: "#334155",
                  color: "#ffffff",
                  border: "none",
                  borderRadius: "4px",
                  fontSize: "0.8rem",
                  fontWeight: 700,
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: "6px",
                }}
              >
                <i className="fa-solid fa-download"></i> Download
              </button>
            </div>
          </div>

          <pre
            style={{
              background: "#020617",
              padding: "16px",
              borderRadius: "4px",
              fontSize: "0.88rem",
              lineHeight: 1.6,
              overflowX: "auto",
              color: "#38bdf8",
              fontFamily: "monospace",
              margin: 0,
              minHeight: "260px",
              border: "1px solid #1e293b",
            }}
          >
            {generatedCode}
          </pre>
        </div>
      </div>

      {/* FAQ ACCORDION */}
      <ToolFaqAccordion faqs={faqs} title="301 Redirects &amp; Server Configuration FAQ" />
    </div>
  );
}
